package renderer

import (
	"bytes"
	"fmt"
	"regexp"
	"strings"

	"github.com/alciller88/commitlore/internal/changelog"
	"github.com/alciller88/commitlore/internal/git"
	"github.com/jung-kurt/gofpdf"
)

const (
	pdfMargin     = 15.0
	pdfFontSize   = 10.0
	pdfTitleSize  = 18.0
	pdfH2Size     = 14.0
	pdfLineHeight = 6.0
)

var emojiPattern = regexp.MustCompile(`[\x{1F000}-\x{1FFFF}]|[\x{2600}-\x{27BF}]|[\x{FE00}-\x{FE0F}]|[\x{200D}]`)

func renderChangelogPDF(content string, cl changelog.Changelog) (string, error) {
	pdf := newPDF()
	writePDFTitle(pdf, "Changelog")
	for _, g := range cl.Groups {
		writePDFGroupHeader(pdf, groupTitle(g.Type))
		writePDFCommits(pdf, g.Commits)
	}
	writePDFFooter(pdf)
	return pdfToString(pdf)
}

func renderStoryPDF(content string, ch git.Chronology) (string, error) {
	pdf := newPDF()
	writePDFTitle(pdf, "Repository Story")
	writeStoryIntroPDF(pdf, ch)
	writeStoryTagsPDF(pdf, ch)
	writeStoryPeaksPDF(pdf, ch)
	writeStoryContributorsPDF(pdf, ch)
	writePDFFooter(pdf)
	return pdfToString(pdf)
}

func newPDF() *gofpdf.Fpdf {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(pdfMargin, pdfMargin, pdfMargin)
	pdf.AddPage()
	pdf.SetAutoPageBreak(true, pdfMargin)
	return pdf
}

func pdfContentWidth(pdf *gofpdf.Fpdf) float64 {
	w, _ := pdf.GetPageSize()
	left, _, right, _ := pdf.GetMargins()
	return w - left - right
}

func writePDFTitle(pdf *gofpdf.Fpdf, title string) {
	pdf.SetFont("Helvetica", "B", pdfTitleSize)
	tr := pdf.UnicodeTranslatorFromDescriptor("")
	pdf.CellFormat(0, 10, tr(stripEmojis(title)), "", 1, "L", false, 0, "")
	pdf.Ln(4)
	drawPDFLine(pdf)
	pdf.Ln(4)
}

func writePDFGroupHeader(pdf *gofpdf.Fpdf, title string) {
	pdf.Ln(3)
	pdf.SetFont("Helvetica", "B", pdfH2Size)
	tr := pdf.UnicodeTranslatorFromDescriptor("")
	pdf.CellFormat(0, 8, tr(stripEmojis(title)), "", 1, "L", false, 0, "")
	pdf.Ln(2)
}

func writePDFCommits(pdf *gofpdf.Fpdf, commits []changelog.ParsedCommit) {
	pdf.SetFont("Helvetica", "", pdfFontSize)
	tr := pdf.UnicodeTranslatorFromDescriptor("")
	w := pdfContentWidth(pdf)
	for _, c := range commits {
		line := tr(stripEmojis(formatCommitLine(c)))
		pdf.MultiCell(w, pdfLineHeight, line, "", "L", false)
	}
}

func formatCommitLine(c changelog.ParsedCommit) string {
	hash := shortHash(c.Hash)
	return fmt.Sprintf("[%s] %s (%s) - %s",
		strings.ToUpper(string(c.Type)), c.Message, c.Author, hash)
}

func writeStoryIntroPDF(pdf *gofpdf.Fpdf, ch git.Chronology) {
	if ch.TotalCommits == 0 {
		return
	}
	pdf.SetFont("Helvetica", "", pdfFontSize)
	tr := pdf.UnicodeTranslatorFromDescriptor("")
	w := pdfContentWidth(pdf)
	line := fmt.Sprintf("Started on %s by %s. Total commits: %d. Contributors: %d.",
		ch.FirstCommit.Date.Format("2006-01-02"),
		ch.FirstCommit.Author,
		ch.TotalCommits,
		len(ch.Contributors))
	pdf.MultiCell(w, pdfLineHeight, tr(stripEmojis(line)), "", "L", false)
	pdf.Ln(2)
}

func writeStoryTagsPDF(pdf *gofpdf.Fpdf, ch git.Chronology) {
	if len(ch.Tags) == 0 {
		return
	}
	writePDFGroupHeader(pdf, "Milestones")
	pdf.SetFont("Helvetica", "", pdfFontSize)
	tr := pdf.UnicodeTranslatorFromDescriptor("")
	w := pdfContentWidth(pdf)
	for _, t := range ch.Tags {
		line := fmt.Sprintf("%s -- %s", t.Name, t.Date.Format("2006-01-02"))
		pdf.MultiCell(w, pdfLineHeight, tr(stripEmojis(line)), "", "L", false)
	}
}

func writeStoryPeaksPDF(pdf *gofpdf.Fpdf, ch git.Chronology) {
	if len(ch.Peaks) == 0 {
		return
	}
	writePDFGroupHeader(pdf, "Activity Peaks")
	pdf.SetFont("Helvetica", "", pdfFontSize)
	tr := pdf.UnicodeTranslatorFromDescriptor("")
	w := pdfContentWidth(pdf)
	for _, p := range ch.Peaks {
		line := fmt.Sprintf("%s -- %d commits", p.Month, p.Count)
		pdf.MultiCell(w, pdfLineHeight, tr(stripEmojis(line)), "", "L", false)
	}
}

func writeStoryContributorsPDF(pdf *gofpdf.Fpdf, ch git.Chronology) {
	if len(ch.Contributors) == 0 {
		return
	}
	writePDFGroupHeader(pdf, "Contributors")
	pdf.SetFont("Helvetica", "", pdfFontSize)
	tr := pdf.UnicodeTranslatorFromDescriptor("")
	w := pdfContentWidth(pdf)
	for _, c := range ch.Contributors {
		line := fmt.Sprintf("%s -- joined %s", c.Name, c.Date.Format("2006-01-02"))
		pdf.MultiCell(w, pdfLineHeight, tr(stripEmojis(line)), "", "L", false)
	}
}

func writePDFFooter(pdf *gofpdf.Fpdf) {
	pdf.Ln(6)
	drawPDFLine(pdf)
	pdf.Ln(2)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.CellFormat(0, pdfLineHeight, "Generated by commitlore", "", 1, "L", false, 0, "")
}

func drawPDFLine(pdf *gofpdf.Fpdf) {
	w, _ := pdf.GetPageSize()
	x := pdf.GetX()
	y := pdf.GetY()
	pdf.Line(x, y, w-pdfMargin, y)
}

func pdfToString(pdf *gofpdf.Fpdf) (string, error) {
	if err := pdf.Error(); err != nil {
		return "", fmt.Errorf("building PDF: %w", err)
	}
	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return "", fmt.Errorf("writing PDF: %w", err)
	}
	return buf.String(), nil
}

func stripEmojis(s string) string {
	return emojiPattern.ReplaceAllString(s, "")
}
