// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChangelogApp exposes changelog generation to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Generate produces a changelog as HTML from the given repo.
 * LLM config is read automatically from Settings (config.yml + keychain).
 * @param {string} repo
 * @param {string} since
 * @param {string} until
 * @param {string} styleName
 * @returns {$CancellablePromise<string>}
 */
export function Generate(repo, since, until, styleName) {
    return $Call.ByID(3798897948, repo, since, until, styleName);
}
