// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigApp manages application configuration for the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddRecentRepo adds a repo to the recent list (max 10, most recent first).
 */
export function AddRecentRepo(path: string, repoType: string): $CancellablePromise<void> {
    return $Call.ByID(1624862341, path, repoType);
}

/**
 * ClearLLMKey removes the API key from the OS keychain.
 */
export function ClearLLMKey(provider: string): $CancellablePromise<void> {
    return $Call.ByID(3501195314, provider);
}

/**
 * GetActiveStyle returns the active style name, default "formal".
 */
export function GetActiveStyle(): $CancellablePromise<string> {
    return $Call.ByID(2766298040);
}

/**
 * GetLLMConfig returns provider, model, and whether a key is configured.
 */
export function GetLLMConfig(): $CancellablePromise<$models.LLMConfig> {
    return $Call.ByID(4043883278).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetRecentRepos returns the list of recent repos from config.
 */
export function GetRecentRepos(): $CancellablePromise<$models.RecentRepo[]> {
    return $Call.ByID(3723375547).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SetActiveStyle saves the active style name to config.yml.
 */
export function SetActiveStyle(name: string): $CancellablePromise<void> {
    return $Call.ByID(1206380740, name);
}

/**
 * SetLLMConfig saves provider and model to config, key to OS keychain.
 */
export function SetLLMConfig(provider: string, model: string, key: string): $CancellablePromise<void> {
    return $Call.ByID(432285218, provider, model, key);
}

// Private type creation functions
const $$createType0 = $models.LLMConfig.createFrom;
const $$createType1 = $models.RecentRepo.createFrom;
const $$createType2 = $Create.Array($$createType1);
