// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigApp manages application configuration for the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddRecentRepo adds a repo to the recent list (max 10, most recent first).
 * @param {string} path
 * @param {string} repoType
 * @returns {$CancellablePromise<void>}
 */
export function AddRecentRepo(path, repoType) {
    return $Call.ByID(1624862341, path, repoType);
}

/**
 * ClearLLMKey removes the API key from the OS keychain.
 * @param {string} provider
 * @returns {$CancellablePromise<void>}
 */
export function ClearLLMKey(provider) {
    return $Call.ByID(3501195314, provider);
}

/**
 * GetActiveStyle returns the active style name, default "formal".
 * @returns {$CancellablePromise<string>}
 */
export function GetActiveStyle() {
    return $Call.ByID(2766298040);
}

/**
 * GetLLMConfig returns provider, model, and whether a key is configured.
 * @returns {$CancellablePromise<$models.LLMConfig>}
 */
export function GetLLMConfig() {
    return $Call.ByID(4043883278).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetLanguage returns the active language, default "en".
 * @returns {$CancellablePromise<string>}
 */
export function GetLanguage() {
    return $Call.ByID(1795821091);
}

/**
 * GetRecentRepos returns the list of recent repos from config.
 * @returns {$CancellablePromise<$models.RecentRepo[]>}
 */
export function GetRecentRepos() {
    return $Call.ByID(3723375547).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * SetActiveStyle saves the active style name to config.yml.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function SetActiveStyle(name) {
    return $Call.ByID(1206380740, name);
}

/**
 * SetLLMConfig saves provider and model to config, key to OS keychain.
 * @param {string} provider
 * @param {string} model
 * @param {string} key
 * @returns {$CancellablePromise<void>}
 */
export function SetLLMConfig(provider, model, key) {
    return $Call.ByID(432285218, provider, model, key);
}

/**
 * SetLanguage validates and saves the language to config.yml.
 * It checks that the currently active style has a variant for
 * the requested language before saving.
 * @param {string} lang
 * @returns {$CancellablePromise<void>}
 */
export function SetLanguage(lang) {
    return $Call.ByID(569478775, lang);
}

// Private type creation functions
const $$createType0 = $models.LLMConfig.createFrom;
const $$createType1 = $models.RecentRepo.createFrom;
const $$createType2 = $Create.Array($$createType1);
