// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GitApp exposes git history and contributor data to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Contributors returns aggregated contributor data as JSON.
 * @param {string} repo
 * @param {string} since
 * @param {number} top
 * @returns {$CancellablePromise<string>}
 */
export function Contributors(repo, since, top) {
    return $Call.ByID(1880363267, repo, since, top);
}

/**
 * History returns commits as JSON, supporting local and GitHub repos.
 * @param {string} repo
 * @param {string} author
 * @param {string} since
 * @param {string} until
 * @param {number} limit
 * @returns {$CancellablePromise<string>}
 */
export function History(repo, author, since, until, limit) {
    return $Call.ByID(2966096151, repo, author, since, until, limit);
}

/**
 * OpenFolderPicker opens a native folder selection dialog.
 * Returns the selected path or empty string if cancelled.
 * @returns {$CancellablePromise<string>}
 */
export function OpenFolderPicker() {
    return $Call.ByID(3331723587);
}
