// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GitApp exposes git history and contributor data to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Contributors returns aggregated contributor data as JSON.
 */
export function Contributors(repo: string, since: string, top: number): $CancellablePromise<string> {
    return $Call.ByID(1880363267, repo, since, top);
}

/**
 * History returns commits as JSON, supporting local and GitHub repos.
 */
export function History(repo: string, author: string, since: string, until: string, limit: number): $CancellablePromise<string> {
    return $Call.ByID(2966096151, repo, author, since, until, limit);
}

/**
 * OpenFolderPicker opens a native folder selection dialog.
 * Returns the selected path or empty string if cancelled.
 */
export function OpenFolderPicker(): $CancellablePromise<string> {
    return $Call.ByID(3331723587);
}
