// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MarketplaceApp exposes marketplace operations to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * FetchCatalog downloads and parses the style catalog from the official repository.
 * @returns {$CancellablePromise<$models.MarketplaceEntry[]>}
 */
export function FetchCatalog() {
    return $Call.ByID(2710032985).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * InstallStyle downloads a .shipstyle from the given URL, validates it,
 * and saves it to the user styles directory.
 * @param {string} downloadURL
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function InstallStyle(downloadURL, name) {
    return $Call.ByID(2614356990, downloadURL, name);
}

/**
 * IsInstalled returns true if a style with the given name exists
 * in the user styles directory.
 * @param {string} name
 * @returns {$CancellablePromise<boolean>}
 */
export function IsInstalled(name) {
    return $Call.ByID(785064928, name);
}

// Private type creation functions
const $$createType0 = $models.MarketplaceEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
