// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ColorsDetail holds the color palette.
 */
export class ColorsDetail {
    "primary": string;
    "secondary": string;
    "background": string;
    "surface": string;
    "text": string;
    "accent": string;
    "border": string;

    /** Creates a new ColorsDetail instance. */
    constructor($$source: Partial<ColorsDetail> = {}) {
        if (!("primary" in $$source)) {
            this["primary"] = "";
        }
        if (!("secondary" in $$source)) {
            this["secondary"] = "";
        }
        if (!("background" in $$source)) {
            this["background"] = "";
        }
        if (!("surface" in $$source)) {
            this["surface"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("accent" in $$source)) {
            this["accent"] = "";
        }
        if (!("border" in $$source)) {
            this["border"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColorsDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): ColorsDetail {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColorsDetail($$parsedSource as Partial<ColorsDetail>);
    }
}

/**
 * DecorDetail holds terminal decorator strings.
 */
export class DecorDetail {
    "separator": string;
    "bullet": string;
    "indent": string;

    /** Creates a new DecorDetail instance. */
    constructor($$source: Partial<DecorDetail> = {}) {
        if (!("separator" in $$source)) {
            this["separator"] = "";
        }
        if (!("bullet" in $$source)) {
            this["bullet"] = "";
        }
        if (!("indent" in $$source)) {
            this["indent"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DecorDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): DecorDetail {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DecorDetail($$parsedSource as Partial<DecorDetail>);
    }
}

/**
 * LLMConfig holds the LLM provider configuration for the frontend.
 */
export class LLMConfig {
    "provider": string;
    "model": string;
    "keyConfigured": boolean;

    /** Creates a new LLMConfig instance. */
    constructor($$source: Partial<LLMConfig> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("keyConfigured" in $$source)) {
            this["keyConfigured"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LLMConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): LLMConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LLMConfig($$parsedSource as Partial<LLMConfig>);
    }
}

/**
 * RecentRepo represents a recently opened repository.
 */
export class RecentRepo {
    "path": string;
    "type": string;
    "lastUsed": string;

    /** Creates a new RecentRepo instance. */
    constructor($$source: Partial<RecentRepo> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("lastUsed" in $$source)) {
            this["lastUsed"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecentRepo instance from a string or object.
     */
    static createFrom($$source: any = {}): RecentRepo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecentRepo($$parsedSource as Partial<RecentRepo>);
    }
}

/**
 * StyleDetail holds all .shipstyle fields for the editor UI.
 */
export class StyleDetail {
    "name": string;
    "version": string;
    "description": string;
    "author": string;
    "llmPrompt": string;
    "tags": string[];
    "previewUrl": string;
    "homepage": string;
    "templates": TemplatesDetail;
    "vocabulary": { [_ in string]?: string };
    "theme": ThemeDetail;
    "terminal": TerminalDetail;

    /** Creates a new StyleDetail instance. */
    constructor($$source: Partial<StyleDetail> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("llmPrompt" in $$source)) {
            this["llmPrompt"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("previewUrl" in $$source)) {
            this["previewUrl"] = "";
        }
        if (!("homepage" in $$source)) {
            this["homepage"] = "";
        }
        if (!("templates" in $$source)) {
            this["templates"] = (new TemplatesDetail());
        }
        if (!("vocabulary" in $$source)) {
            this["vocabulary"] = {};
        }
        if (!("theme" in $$source)) {
            this["theme"] = (new ThemeDetail());
        }
        if (!("terminal" in $$source)) {
            this["terminal"] = (new TerminalDetail());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StyleDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): StyleDetail {
        const $$createField5_0 = $$createType0;
        const $$createField8_0 = $$createType1;
        const $$createField9_0 = $$createType2;
        const $$createField10_0 = $$createType3;
        const $$createField11_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField5_0($$parsedSource["tags"]);
        }
        if ("templates" in $$parsedSource) {
            $$parsedSource["templates"] = $$createField8_0($$parsedSource["templates"]);
        }
        if ("vocabulary" in $$parsedSource) {
            $$parsedSource["vocabulary"] = $$createField9_0($$parsedSource["vocabulary"]);
        }
        if ("theme" in $$parsedSource) {
            $$parsedSource["theme"] = $$createField10_0($$parsedSource["theme"]);
        }
        if ("terminal" in $$parsedSource) {
            $$parsedSource["terminal"] = $$createField11_0($$parsedSource["terminal"]);
        }
        return new StyleDetail($$parsedSource as Partial<StyleDetail>);
    }
}

/**
 * StyleTheme holds the theme fields for frontend CSS variable injection.
 */
export class StyleTheme {
    "primary": string;
    "secondary": string;
    "background": string;
    "surface": string;
    "text": string;
    "accent": string;
    "border": string;
    "fontFamily": string;
    "fontSize": string;
    "mode": string;
    "logo": string;
    "winDefault": string;
    "winClose": string;
    "winMinimize": string;
    "winMaximize": string;

    /** Creates a new StyleTheme instance. */
    constructor($$source: Partial<StyleTheme> = {}) {
        if (!("primary" in $$source)) {
            this["primary"] = "";
        }
        if (!("secondary" in $$source)) {
            this["secondary"] = "";
        }
        if (!("background" in $$source)) {
            this["background"] = "";
        }
        if (!("surface" in $$source)) {
            this["surface"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("accent" in $$source)) {
            this["accent"] = "";
        }
        if (!("border" in $$source)) {
            this["border"] = "";
        }
        if (!("fontFamily" in $$source)) {
            this["fontFamily"] = "";
        }
        if (!("fontSize" in $$source)) {
            this["fontSize"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("logo" in $$source)) {
            this["logo"] = "";
        }
        if (!("winDefault" in $$source)) {
            this["winDefault"] = "";
        }
        if (!("winClose" in $$source)) {
            this["winClose"] = "";
        }
        if (!("winMinimize" in $$source)) {
            this["winMinimize"] = "";
        }
        if (!("winMaximize" in $$source)) {
            this["winMaximize"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StyleTheme instance from a string or object.
     */
    static createFrom($$source: any = {}): StyleTheme {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StyleTheme($$parsedSource as Partial<StyleTheme>);
    }
}

/**
 * TemplatesDetail holds all template strings.
 */
export class TemplatesDetail {
    "header": string;
    "feature": string;
    "fix": string;
    "breaking": string;
    "footer": string;
    "storyIntro": string;
    "storyMilestone": string;
    "storyPeak": string;
    "storyContributor": string;
    "storyFooter": string;

    /** Creates a new TemplatesDetail instance. */
    constructor($$source: Partial<TemplatesDetail> = {}) {
        if (!("header" in $$source)) {
            this["header"] = "";
        }
        if (!("feature" in $$source)) {
            this["feature"] = "";
        }
        if (!("fix" in $$source)) {
            this["fix"] = "";
        }
        if (!("breaking" in $$source)) {
            this["breaking"] = "";
        }
        if (!("footer" in $$source)) {
            this["footer"] = "";
        }
        if (!("storyIntro" in $$source)) {
            this["storyIntro"] = "";
        }
        if (!("storyMilestone" in $$source)) {
            this["storyMilestone"] = "";
        }
        if (!("storyPeak" in $$source)) {
            this["storyPeak"] = "";
        }
        if (!("storyContributor" in $$source)) {
            this["storyContributor"] = "";
        }
        if (!("storyFooter" in $$source)) {
            this["storyFooter"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TemplatesDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): TemplatesDetail {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TemplatesDetail($$parsedSource as Partial<TemplatesDetail>);
    }
}

/**
 * TermColorsDetail holds terminal ANSI color names.
 */
export class TermColorsDetail {
    "header": string;
    "feature": string;
    "fix": string;
    "breaking": string;
    "footer": string;

    /** Creates a new TermColorsDetail instance. */
    constructor($$source: Partial<TermColorsDetail> = {}) {
        if (!("header" in $$source)) {
            this["header"] = "";
        }
        if (!("feature" in $$source)) {
            this["feature"] = "";
        }
        if (!("fix" in $$source)) {
            this["fix"] = "";
        }
        if (!("breaking" in $$source)) {
            this["breaking"] = "";
        }
        if (!("footer" in $$source)) {
            this["footer"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TermColorsDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): TermColorsDetail {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TermColorsDetail($$parsedSource as Partial<TermColorsDetail>);
    }
}

/**
 * TerminalDetail holds terminal visual identity.
 */
export class TerminalDetail {
    "colors": TermColorsDetail;
    "decorators": DecorDetail;
    "density": string;

    /** Creates a new TerminalDetail instance. */
    constructor($$source: Partial<TerminalDetail> = {}) {
        if (!("colors" in $$source)) {
            this["colors"] = (new TermColorsDetail());
        }
        if (!("decorators" in $$source)) {
            this["decorators"] = (new DecorDetail());
        }
        if (!("density" in $$source)) {
            this["density"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): TerminalDetail {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("colors" in $$parsedSource) {
            $$parsedSource["colors"] = $$createField0_0($$parsedSource["colors"]);
        }
        if ("decorators" in $$parsedSource) {
            $$parsedSource["decorators"] = $$createField1_0($$parsedSource["decorators"]);
        }
        return new TerminalDetail($$parsedSource as Partial<TerminalDetail>);
    }
}

/**
 * ThemeDetail holds all theme fields.
 */
export class ThemeDetail {
    "mode": string;
    "colors": ColorsDetail;
    "typography": TypoDetail;
    "headerImage": string;
    "logo": string;
    "cardStyle": string;
    "animations": boolean;
    "customCss": string;
    "windowControls": WinControlDetail;

    /** Creates a new ThemeDetail instance. */
    constructor($$source: Partial<ThemeDetail> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("colors" in $$source)) {
            this["colors"] = (new ColorsDetail());
        }
        if (!("typography" in $$source)) {
            this["typography"] = (new TypoDetail());
        }
        if (!("headerImage" in $$source)) {
            this["headerImage"] = "";
        }
        if (!("logo" in $$source)) {
            this["logo"] = "";
        }
        if (!("cardStyle" in $$source)) {
            this["cardStyle"] = "";
        }
        if (!("animations" in $$source)) {
            this["animations"] = false;
        }
        if (!("customCss" in $$source)) {
            this["customCss"] = "";
        }
        if (!("windowControls" in $$source)) {
            this["windowControls"] = (new WinControlDetail());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemeDetail {
        const $$createField1_0 = $$createType7;
        const $$createField2_0 = $$createType8;
        const $$createField8_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("colors" in $$parsedSource) {
            $$parsedSource["colors"] = $$createField1_0($$parsedSource["colors"]);
        }
        if ("typography" in $$parsedSource) {
            $$parsedSource["typography"] = $$createField2_0($$parsedSource["typography"]);
        }
        if ("windowControls" in $$parsedSource) {
            $$parsedSource["windowControls"] = $$createField8_0($$parsedSource["windowControls"]);
        }
        return new ThemeDetail($$parsedSource as Partial<ThemeDetail>);
    }
}

/**
 * TypoDetail holds typography fields.
 */
export class TypoDetail {
    "fontFamily": string;
    "fontSizeBase": string;
    "fontSizeHeader": string;
    "fontSizeCode": string;

    /** Creates a new TypoDetail instance. */
    constructor($$source: Partial<TypoDetail> = {}) {
        if (!("fontFamily" in $$source)) {
            this["fontFamily"] = "";
        }
        if (!("fontSizeBase" in $$source)) {
            this["fontSizeBase"] = "";
        }
        if (!("fontSizeHeader" in $$source)) {
            this["fontSizeHeader"] = "";
        }
        if (!("fontSizeCode" in $$source)) {
            this["fontSizeCode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TypoDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): TypoDetail {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TypoDetail($$parsedSource as Partial<TypoDetail>);
    }
}

/**
 * WinControlDetail holds window control colors.
 */
export class WinControlDetail {
    "default": string;
    "close": string;
    "minimize": string;
    "maximize": string;

    /** Creates a new WinControlDetail instance. */
    constructor($$source: Partial<WinControlDetail> = {}) {
        if (!("default" in $$source)) {
            this["default"] = "";
        }
        if (!("close" in $$source)) {
            this["close"] = "";
        }
        if (!("minimize" in $$source)) {
            this["minimize"] = "";
        }
        if (!("maximize" in $$source)) {
            this["maximize"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WinControlDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): WinControlDetail {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WinControlDetail($$parsedSource as Partial<WinControlDetail>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = TemplatesDetail.createFrom;
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = ThemeDetail.createFrom;
const $$createType4 = TerminalDetail.createFrom;
const $$createType5 = TermColorsDetail.createFrom;
const $$createType6 = DecorDetail.createFrom;
const $$createType7 = ColorsDetail.createFrom;
const $$createType8 = TypoDetail.createFrom;
const $$createType9 = WinControlDetail.createFrom;
