// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * LLMConfig holds the LLM provider configuration for the frontend.
 */
export class LLMConfig {
    /**
     * Creates a new LLMConfig instance.
     * @param {Partial<LLMConfig>} [$$source = {}] - The source object to create the LLMConfig.
     */
    constructor($$source = {}) {
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("keyConfigured" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["keyConfigured"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LLMConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LLMConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LLMConfig(/** @type {Partial<LLMConfig>} */($$parsedSource));
    }
}

/**
 * RecentRepo represents a recently opened repository.
 */
export class RecentRepo {
    /**
     * Creates a new RecentRepo instance.
     * @param {Partial<RecentRepo>} [$$source = {}] - The source object to create the RecentRepo.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("lastUsed" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastUsed"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecentRepo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RecentRepo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecentRepo(/** @type {Partial<RecentRepo>} */($$parsedSource));
    }
}

/**
 * StyleTheme holds the theme fields for frontend CSS variable injection.
 */
export class StyleTheme {
    /**
     * Creates a new StyleTheme instance.
     * @param {Partial<StyleTheme>} [$$source = {}] - The source object to create the StyleTheme.
     */
    constructor($$source = {}) {
        if (!("primary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["primary"] = "";
        }
        if (!("secondary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["secondary"] = "";
        }
        if (!("background" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["background"] = "";
        }
        if (!("surface" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["surface"] = "";
        }
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("accent" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["accent"] = "";
        }
        if (!("border" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["border"] = "";
        }
        if (!("fontFamily" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fontFamily"] = "";
        }
        if (!("fontSize" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fontSize"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("logo" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["logo"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StyleTheme instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StyleTheme}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StyleTheme(/** @type {Partial<StyleTheme>} */($$parsedSource));
    }
}
