// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ColorsDetail holds the color palette.
 */
export class ColorsDetail {
    /**
     * Creates a new ColorsDetail instance.
     * @param {Partial<ColorsDetail>} [$$source = {}] - The source object to create the ColorsDetail.
     */
    constructor($$source = {}) {
        if (!("primary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["primary"] = "";
        }
        if (!("secondary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["secondary"] = "";
        }
        if (!("background" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["background"] = "";
        }
        if (!("surface" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["surface"] = "";
        }
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("accent" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["accent"] = "";
        }
        if (!("border" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["border"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColorsDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ColorsDetail}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColorsDetail(/** @type {Partial<ColorsDetail>} */($$parsedSource));
    }
}

/**
 * DecorDetail holds terminal decorator strings.
 */
export class DecorDetail {
    /**
     * Creates a new DecorDetail instance.
     * @param {Partial<DecorDetail>} [$$source = {}] - The source object to create the DecorDetail.
     */
    constructor($$source = {}) {
        if (!("separator" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["separator"] = "";
        }
        if (!("bullet" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bullet"] = "";
        }
        if (!("indent" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["indent"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DecorDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DecorDetail}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DecorDetail(/** @type {Partial<DecorDetail>} */($$parsedSource));
    }
}

/**
 * IconsDetail holds per-style icon/emoji characters.
 */
export class IconsDetail {
    /**
     * Creates a new IconsDetail instance.
     * @param {Partial<IconsDetail>} [$$source = {}] - The source object to create the IconsDetail.
     */
    constructor($$source = {}) {
        if (!("feature" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["feature"] = "";
        }
        if (!("fix" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fix"] = "";
        }
        if (!("breaking" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["breaking"] = "";
        }
        if (!("chore" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["chore"] = "";
        }
        if (!("docs" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["docs"] = "";
        }
        if (!("test" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["test"] = "";
        }
        if (!("storyPeak" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["storyPeak"] = "";
        }
        if (!("bullet" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bullet"] = "";
        }
        if (!("separator" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["separator"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IconsDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IconsDetail}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IconsDetail(/** @type {Partial<IconsDetail>} */($$parsedSource));
    }
}

/**
 * LLMConfig holds the LLM provider configuration for the frontend.
 */
export class LLMConfig {
    /**
     * Creates a new LLMConfig instance.
     * @param {Partial<LLMConfig>} [$$source = {}] - The source object to create the LLMConfig.
     */
    constructor($$source = {}) {
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("keyConfigured" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["keyConfigured"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LLMConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LLMConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LLMConfig(/** @type {Partial<LLMConfig>} */($$parsedSource));
    }
}

/**
 * MarketplaceEntry represents a single style in the catalog.
 */
export class MarketplaceEntry {
    /**
     * Creates a new MarketplaceEntry instance.
     * @param {Partial<MarketplaceEntry>} [$$source = {}] - The source object to create the MarketplaceEntry.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("preview" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["preview"] = "";
        }
        if (!("download" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["download"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MarketplaceEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MarketplaceEntry}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        return new MarketplaceEntry(/** @type {Partial<MarketplaceEntry>} */($$parsedSource));
    }
}

/**
 * RecentRepo represents a recently opened repository.
 */
export class RecentRepo {
    /**
     * Creates a new RecentRepo instance.
     * @param {Partial<RecentRepo>} [$$source = {}] - The source object to create the RecentRepo.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("lastUsed" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastUsed"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecentRepo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RecentRepo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecentRepo(/** @type {Partial<RecentRepo>} */($$parsedSource));
    }
}

/**
 * StyleDetail holds all .shipstyle fields for the editor UI.
 */
export class StyleDetail {
    /**
     * Creates a new StyleDetail instance.
     * @param {Partial<StyleDetail>} [$$source = {}] - The source object to create the StyleDetail.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("llmPrompt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["llmPrompt"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("previewUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["previewUrl"] = "";
        }
        if (!("homepage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["homepage"] = "";
        }
        if (!("templates" in $$source)) {
            /**
             * @member
             * @type {TemplatesDetail}
             */
            this["templates"] = (new TemplatesDetail());
        }
        if (!("vocabulary" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["vocabulary"] = {};
        }
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {ThemeDetail}
             */
            this["theme"] = (new ThemeDetail());
        }
        if (!("terminal" in $$source)) {
            /**
             * @member
             * @type {TerminalDetail}
             */
            this["terminal"] = (new TerminalDetail());
        }
        if (!("uiLabels" in $$source)) {
            /**
             * @member
             * @type {UILabelsDetail}
             */
            this["uiLabels"] = (new UILabelsDetail());
        }
        if (!("icons" in $$source)) {
            /**
             * @member
             * @type {IconsDetail}
             */
            this["icons"] = (new IconsDetail());
        }
        if (!("htmlTemplateChangelog" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["htmlTemplateChangelog"] = "";
        }
        if (!("htmlTemplateStory" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["htmlTemplateStory"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StyleDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StyleDetail}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        const $$createField8_0 = $$createType1;
        const $$createField9_0 = $$createType2;
        const $$createField10_0 = $$createType3;
        const $$createField11_0 = $$createType4;
        const $$createField12_0 = $$createType5;
        const $$createField13_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField5_0($$parsedSource["tags"]);
        }
        if ("templates" in $$parsedSource) {
            $$parsedSource["templates"] = $$createField8_0($$parsedSource["templates"]);
        }
        if ("vocabulary" in $$parsedSource) {
            $$parsedSource["vocabulary"] = $$createField9_0($$parsedSource["vocabulary"]);
        }
        if ("theme" in $$parsedSource) {
            $$parsedSource["theme"] = $$createField10_0($$parsedSource["theme"]);
        }
        if ("terminal" in $$parsedSource) {
            $$parsedSource["terminal"] = $$createField11_0($$parsedSource["terminal"]);
        }
        if ("uiLabels" in $$parsedSource) {
            $$parsedSource["uiLabels"] = $$createField12_0($$parsedSource["uiLabels"]);
        }
        if ("icons" in $$parsedSource) {
            $$parsedSource["icons"] = $$createField13_0($$parsedSource["icons"]);
        }
        return new StyleDetail(/** @type {Partial<StyleDetail>} */($$parsedSource));
    }
}

/**
 * StyleTheme holds the theme fields for frontend CSS variable injection.
 */
export class StyleTheme {
    /**
     * Creates a new StyleTheme instance.
     * @param {Partial<StyleTheme>} [$$source = {}] - The source object to create the StyleTheme.
     */
    constructor($$source = {}) {
        if (!("primary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["primary"] = "";
        }
        if (!("secondary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["secondary"] = "";
        }
        if (!("background" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["background"] = "";
        }
        if (!("surface" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["surface"] = "";
        }
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("accent" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["accent"] = "";
        }
        if (!("border" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["border"] = "";
        }
        if (!("fontFamily" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fontFamily"] = "";
        }
        if (!("fontSize" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fontSize"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("logo" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["logo"] = "";
        }
        if (!("winDefault" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["winDefault"] = "";
        }
        if (!("winClose" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["winClose"] = "";
        }
        if (!("winMinimize" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["winMinimize"] = "";
        }
        if (!("winMaximize" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["winMaximize"] = "";
        }
        if (!("uiLabels" in $$source)) {
            /**
             * @member
             * @type {UILabelsDetail}
             */
            this["uiLabels"] = (new UILabelsDetail());
        }
        if (!("icons" in $$source)) {
            /**
             * @member
             * @type {IconsDetail}
             */
            this["icons"] = (new IconsDetail());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StyleTheme instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StyleTheme}
     */
    static createFrom($$source = {}) {
        const $$createField15_0 = $$createType5;
        const $$createField16_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("uiLabels" in $$parsedSource) {
            $$parsedSource["uiLabels"] = $$createField15_0($$parsedSource["uiLabels"]);
        }
        if ("icons" in $$parsedSource) {
            $$parsedSource["icons"] = $$createField16_0($$parsedSource["icons"]);
        }
        return new StyleTheme(/** @type {Partial<StyleTheme>} */($$parsedSource));
    }
}

/**
 * TemplatesDetail holds all template strings.
 */
export class TemplatesDetail {
    /**
     * Creates a new TemplatesDetail instance.
     * @param {Partial<TemplatesDetail>} [$$source = {}] - The source object to create the TemplatesDetail.
     */
    constructor($$source = {}) {
        if (!("header" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["header"] = "";
        }
        if (!("feature" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["feature"] = "";
        }
        if (!("fix" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fix"] = "";
        }
        if (!("breaking" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["breaking"] = "";
        }
        if (!("footer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["footer"] = "";
        }
        if (!("storyIntro" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["storyIntro"] = "";
        }
        if (!("storyMilestone" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["storyMilestone"] = "";
        }
        if (!("storyPeak" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["storyPeak"] = "";
        }
        if (!("storyContributor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["storyContributor"] = "";
        }
        if (!("storyFooter" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["storyFooter"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TemplatesDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TemplatesDetail}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TemplatesDetail(/** @type {Partial<TemplatesDetail>} */($$parsedSource));
    }
}

/**
 * TermColorsDetail holds terminal ANSI color names.
 */
export class TermColorsDetail {
    /**
     * Creates a new TermColorsDetail instance.
     * @param {Partial<TermColorsDetail>} [$$source = {}] - The source object to create the TermColorsDetail.
     */
    constructor($$source = {}) {
        if (!("header" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["header"] = "";
        }
        if (!("feature" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["feature"] = "";
        }
        if (!("fix" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fix"] = "";
        }
        if (!("breaking" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["breaking"] = "";
        }
        if (!("footer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["footer"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TermColorsDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TermColorsDetail}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TermColorsDetail(/** @type {Partial<TermColorsDetail>} */($$parsedSource));
    }
}

/**
 * TerminalDetail holds terminal visual identity.
 */
export class TerminalDetail {
    /**
     * Creates a new TerminalDetail instance.
     * @param {Partial<TerminalDetail>} [$$source = {}] - The source object to create the TerminalDetail.
     */
    constructor($$source = {}) {
        if (!("colors" in $$source)) {
            /**
             * @member
             * @type {TermColorsDetail}
             */
            this["colors"] = (new TermColorsDetail());
        }
        if (!("decorators" in $$source)) {
            /**
             * @member
             * @type {DecorDetail}
             */
            this["decorators"] = (new DecorDetail());
        }
        if (!("density" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["density"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalDetail}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType7;
        const $$createField1_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("colors" in $$parsedSource) {
            $$parsedSource["colors"] = $$createField0_0($$parsedSource["colors"]);
        }
        if ("decorators" in $$parsedSource) {
            $$parsedSource["decorators"] = $$createField1_0($$parsedSource["decorators"]);
        }
        return new TerminalDetail(/** @type {Partial<TerminalDetail>} */($$parsedSource));
    }
}

/**
 * ThemeDetail holds all theme fields.
 */
export class ThemeDetail {
    /**
     * Creates a new ThemeDetail instance.
     * @param {Partial<ThemeDetail>} [$$source = {}] - The source object to create the ThemeDetail.
     */
    constructor($$source = {}) {
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("colors" in $$source)) {
            /**
             * @member
             * @type {ColorsDetail}
             */
            this["colors"] = (new ColorsDetail());
        }
        if (!("typography" in $$source)) {
            /**
             * @member
             * @type {TypoDetail}
             */
            this["typography"] = (new TypoDetail());
        }
        if (!("headerImage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["headerImage"] = "";
        }
        if (!("logo" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["logo"] = "";
        }
        if (!("cardStyle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cardStyle"] = "";
        }
        if (!("animations" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["animations"] = false;
        }
        if (!("customCss" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["customCss"] = "";
        }
        if (!("windowControls" in $$source)) {
            /**
             * @member
             * @type {WinControlDetail}
             */
            this["windowControls"] = (new WinControlDetail());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThemeDetail}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType9;
        const $$createField2_0 = $$createType10;
        const $$createField8_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("colors" in $$parsedSource) {
            $$parsedSource["colors"] = $$createField1_0($$parsedSource["colors"]);
        }
        if ("typography" in $$parsedSource) {
            $$parsedSource["typography"] = $$createField2_0($$parsedSource["typography"]);
        }
        if ("windowControls" in $$parsedSource) {
            $$parsedSource["windowControls"] = $$createField8_0($$parsedSource["windowControls"]);
        }
        return new ThemeDetail(/** @type {Partial<ThemeDetail>} */($$parsedSource));
    }
}

/**
 * TypoDetail holds typography fields.
 */
export class TypoDetail {
    /**
     * Creates a new TypoDetail instance.
     * @param {Partial<TypoDetail>} [$$source = {}] - The source object to create the TypoDetail.
     */
    constructor($$source = {}) {
        if (!("fontFamily" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fontFamily"] = "";
        }
        if (!("fontSizeBase" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fontSizeBase"] = "";
        }
        if (!("fontSizeHeader" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fontSizeHeader"] = "";
        }
        if (!("fontSizeCode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fontSizeCode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TypoDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TypoDetail}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TypoDetail(/** @type {Partial<TypoDetail>} */($$parsedSource));
    }
}

/**
 * UILabelsDetail holds navigation label overrides for the frontend.
 */
export class UILabelsDetail {
    /**
     * Creates a new UILabelsDetail instance.
     * @param {Partial<UILabelsDetail>} [$$source = {}] - The source object to create the UILabelsDetail.
     */
    constructor($$source = {}) {
        if (!("dashboard" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dashboard"] = "";
        }
        if (!("generate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["generate"] = "";
        }
        if (!("story" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["story"] = "";
        }
        if (!("history" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["history"] = "";
        }
        if (!("contributors" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contributors"] = "";
        }
        if (!("styles" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["styles"] = "";
        }
        if (!("marketplace" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["marketplace"] = "";
        }
        if (!("settings" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["settings"] = "";
        }
        if (!("generateButton" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["generateButton"] = "";
        }
        if (!("storyButton" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["storyButton"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UILabelsDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UILabelsDetail}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UILabelsDetail(/** @type {Partial<UILabelsDetail>} */($$parsedSource));
    }
}

/**
 * WinControlDetail holds window control colors.
 */
export class WinControlDetail {
    /**
     * Creates a new WinControlDetail instance.
     * @param {Partial<WinControlDetail>} [$$source = {}] - The source object to create the WinControlDetail.
     */
    constructor($$source = {}) {
        if (!("default" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["default"] = "";
        }
        if (!("close" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["close"] = "";
        }
        if (!("minimize" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["minimize"] = "";
        }
        if (!("maximize" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["maximize"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WinControlDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WinControlDetail}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WinControlDetail(/** @type {Partial<WinControlDetail>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = TemplatesDetail.createFrom;
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = ThemeDetail.createFrom;
const $$createType4 = TerminalDetail.createFrom;
const $$createType5 = UILabelsDetail.createFrom;
const $$createType6 = IconsDetail.createFrom;
const $$createType7 = TermColorsDetail.createFrom;
const $$createType8 = DecorDetail.createFrom;
const $$createType9 = ColorsDetail.createFrom;
const $$createType10 = TypoDetail.createFrom;
const $$createType11 = WinControlDetail.createFrom;
