// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StoryApp exposes story generation to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GenerateStory produces a narrative as HTML from the given repo.
 * LLM config is read automatically from Settings (config.yml + keychain).
 * @param {string} repo
 * @param {string} $from
 * @param {string} styleName
 * @returns {$CancellablePromise<string>}
 */
export function GenerateStory(repo, $from, styleName) {
    return $Call.ByID(1571363160, repo, $from, styleName);
}
