// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StyleApp exposes style management to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateStyle creates a new user style with the given parameters.
 */
export function CreateStyle(name: string, description: string, author: string): $CancellablePromise<void> {
    return $Call.ByID(3391032965, name, description, author);
}

/**
 * DeleteStyle removes a user-installed style.
 */
export function DeleteStyle(name: string): $CancellablePromise<void> {
    return $Call.ByID(3507572864, name);
}

/**
 * ExportStyle exports a style to the given output path.
 */
export function ExportStyle(name: string, output: string): $CancellablePromise<void> {
    return $Call.ByID(459918375, name, output);
}

/**
 * GetStyleDetail returns all fields of a .shipstyle for the editor UI.
 */
export function GetStyleDetail(name: string): $CancellablePromise<$models.StyleDetail> {
    return $Call.ByID(2945748804, name).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetStyleTheme returns only the theme fields for a style, with fallback defaults.
 */
export function GetStyleTheme(name: string): $CancellablePromise<$models.StyleTheme> {
    return $Call.ByID(579919682, name).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ImportStyle imports a style from a local file path.
 */
export function ImportStyle(path: string): $CancellablePromise<string> {
    return $Call.ByID(4009483210, path);
}

/**
 * IsStyleBuiltIn returns true if the given name is a built-in style.
 */
export function IsStyleBuiltIn(name: string): $CancellablePromise<boolean> {
    return $Call.ByID(2321027588, name);
}

/**
 * ListStyles returns all available styles (built-in + user) as JSON.
 */
export function ListStyles(): $CancellablePromise<string> {
    return $Call.ByID(2140763718);
}

/**
 * SaveStyleDetail saves all fields of a user style. Built-in styles are rejected.
 */
export function SaveStyleDetail(detail: $models.StyleDetail): $CancellablePromise<void> {
    return $Call.ByID(2713249251, detail);
}

/**
 * ShowStyle returns the full style definition as JSON.
 */
export function ShowStyle(name: string): $CancellablePromise<string> {
    return $Call.ByID(4012068334, name);
}

// Private type creation functions
const $$createType0 = $models.StyleDetail.createFrom;
const $$createType1 = $models.StyleTheme.createFrom;
