// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StyleApp exposes style management to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteStyle removes a user-installed style.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteStyle(name) {
    return $Call.ByID(3507572864, name);
}

/**
 * GetAvailableLanguagesForStyle returns which languages are available for a style.
 * @param {string} name
 * @returns {$CancellablePromise<string[]>}
 */
export function GetAvailableLanguagesForStyle(name) {
    return $Call.ByID(3776920794, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetStyleDetail returns all fields of a .shipstyle for the editor UI.
 * @param {string} name
 * @returns {$CancellablePromise<$models.StyleDetail>}
 */
export function GetStyleDetail(name) {
    return $Call.ByID(2945748804, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetStyleTheme returns only the theme fields for a style, with fallback defaults.
 * Uses the current language from config to resolve the correct variant.
 * @param {string} name
 * @returns {$CancellablePromise<$models.StyleTheme>}
 */
export function GetStyleTheme(name) {
    return $Call.ByID(579919682, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * IsStyleBuiltIn returns true if the given name is a built-in style.
 * @param {string} name
 * @returns {$CancellablePromise<boolean>}
 */
export function IsStyleBuiltIn(name) {
    return $Call.ByID(2321027588, name);
}

/**
 * ListStyles returns all available styles (built-in + user) as JSON.
 * @returns {$CancellablePromise<string>}
 */
export function ListStyles() {
    return $Call.ByID(2140763718);
}

/**
 * SaveStyleDetail saves all fields of a user style. Built-in styles are rejected.
 * @param {$models.StyleDetail} detail
 * @returns {$CancellablePromise<void>}
 */
export function SaveStyleDetail(detail) {
    return $Call.ByID(2713249251, detail);
}

/**
 * ShowStyle returns the full style definition as JSON.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function ShowStyle(name) {
    return $Call.ByID(4012068334, name);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.StyleDetail.createFrom;
const $$createType2 = $models.StyleTheme.createFrom;
