// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StyleApp exposes style management to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateStyle creates a new user style with the given parameters.
 * @param {string} name
 * @param {string} description
 * @param {string} author
 * @returns {$CancellablePromise<void>}
 */
export function CreateStyle(name, description, author) {
    return $Call.ByID(3391032965, name, description, author);
}

/**
 * DeleteStyle removes a user-installed style.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteStyle(name) {
    return $Call.ByID(3507572864, name);
}

/**
 * ExportStyle exports a style to the given output path.
 * @param {string} name
 * @param {string} output
 * @returns {$CancellablePromise<void>}
 */
export function ExportStyle(name, output) {
    return $Call.ByID(459918375, name, output);
}

/**
 * GetStyleTheme returns only the theme fields for a style, with fallback defaults.
 * @param {string} name
 * @returns {$CancellablePromise<$models.StyleTheme>}
 */
export function GetStyleTheme(name) {
    return $Call.ByID(579919682, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ImportStyle imports a style from a local file path.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ImportStyle(path) {
    return $Call.ByID(4009483210, path);
}

/**
 * ListStyles returns all available styles (built-in + user) as JSON.
 * @returns {$CancellablePromise<string>}
 */
export function ListStyles() {
    return $Call.ByID(2140763718);
}

/**
 * ShowStyle returns the full style definition as JSON.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function ShowStyle(name) {
    return $Call.ByID(4012068334, name);
}

// Private type creation functions
const $$createType0 = $models.StyleTheme.createFrom;
